### ISSUE TITLE
Support for TLS_ALPN.

### ISSUE THREAD

**Issue by futursolo** [DinoTools/python-flextls#13]
This SSL Library needs TLS_ALPN support that is necessary for HTTP/2.

https://tools.ietf.org/html/rfc7301

**Comment by phibos** [comment]
Sounds good. Looking forward to add initial TLS_ALPN support soon.

**Comment by phibos** [comment]
I have added initial ALPN support. But I have to do some additional tests before merging it into the master branch.

**Comment by phibos** [comment]
ALPN and Next Protocol Negotiation support has been added to FlexTLS and pySSLScan
